### ISSUE TITLE
Place_Order Issue

### ISSUE THREAD

**Issue by convexity2020** [dydxprotocol/dydx-python#51]
Python Installation: 3.6.0

Error message when attempting to submit an order.

`
>>> created_order = client.place_order(
...     market=consts.PAIR_PBTC_USDC,
...     side=consts.SIDE_BUY,
...     amount=utils.btc_to_sats(.1),
...     price=Decimal('72.34'),
...     fillOrKill=False,
...     postOnly=False)
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\dydx\client.py", line 658, in place_order
    'order': order_api_request
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\dydx\client.py", line 57, in _post
    return self._request('post', *args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\dydx\client.py", line 50, in _request
    raise DydxAPIError(response)
dydx.exceptions.DydxAPIError: DydxAPIError(status_code=400)(response={'errors': [{'param': '_error', 'msg': 'Invalid value(s)', 'nestedErrors': [{'location': 'body', 'param': 'order.baseMarket', 'msg': 'Invalid value'}, {'location': 'body', 'param': 'order.quoteMarket', 'msg': 'Invalid value'}, {'location': 'body', 'param': 'order.amount', 'value': '10000000.0', 'msg': 'Invalid value'}, {'location': 'body', 'param': 'order.makerAccountNumber', 'msg': 'Invalid value'}, {'location': 'body', 'param': 'order.makerAccountOwner', 'msg': 'Invalid value'}, {'location': 'body', 'param': 'order.makerAccountOwner', 'msg': 'Invalid value'}, {'location': 'body', 'param': 'order.amount', 'value': '10000000.0', 'msg': 'Invalid value'}]}]})

`

**Comment by alexberdreal** [comment]
Have you fixed it?
